name: pipe

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -D clean package -DskipTests
      - name: Maven verify
        run: mvn -D clean verify

  sonar:
    needs: compile

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: SonarCloud Scan
        run: mvn -D clean verify -Psonar -Dsonar.login=${{secrets.SONAR_TOKEN}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}